@model MvcApplication6.Models.reclutador

@{
    ViewBag.Title = "Consultar reclutadores";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
    
<link href= "@Url.Content("~/Content/css/plugins/dataTables/dataTables.bootstrap.css")" rel="stylesheet">
<script src="@Url.Content("~/Scripts/plugins/dataTables/jquery.dataTables.js")"></script>
<script src="@Url.Content("~/Scripts/Tablas/ConsultarReclutadoresTabla.js")"></script>

<div class="table-responsive">
    <table class="table table-striped table-bordered table-hover" id="reclutadores">
        <thead>
                <tr>
                    <th>Nombre</th>
                    <th>Apellido Paterno</th>
                    <th>Apellido Materno</th>
                    <th>Usuario</th>
                    <th>Permisos</th>
                    <th>id_reclutador</th>
                    <th>opciones</th>
                </tr>
        </thead>
        <tbody>
            @try
            {
                foreach(var rec in ViewBag.reclutadores)
                { 
                    <tr>
                        <td>@rec.persona.nombre</td>
                        <td>@rec.persona.apePaterno</td>
                        <td>@rec.persona.apeMaterno</td>
                        <td>@rec.usuario</td>
                        <td>@Html.Raw(rec.permisos==1 ? "Administrador": "Reclutador")</td>
                        <td id="id_candidato">@rec.idReclutador</td>
                        <td>@Html.ActionLink("Editar", "Edit", new { id=rec.idReclutador }) |
                            @Html.ActionLink("Eliminar", "Delete", new { id=rec.idReclutador })</td>
                    </tr>
                }
            }
            catch (NullReferenceException)
            {
            } 
            catch( Exception)
            {
            } 
        </tbody>
    </table>
</div>

